services:
  api:
    build: .
    container_name: tech-challenge-api
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=mongodb://mongo:27017/tech-challenge-blog
      - JWT_SECRET=suaChaveSecretaSuperForteAqui
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: tech-challenge-db
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: